// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_fcm/shared/configuration/configuration.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: Configuration.webApiKey,
    appId: Configuration.webAppId,
    messagingSenderId: Configuration.messagingSenderId,
    projectId: Configuration.projectId,
    authDomain: Configuration.webAuthDomain,
    storageBucket: Configuration.storageBucket,
    measurementId: Configuration.webMeasurementId,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: Configuration.androidApiKey,
    appId: Configuration.androidAppId,
    messagingSenderId: Configuration.messagingSenderId,
    projectId: Configuration.projectId,
    storageBucket: Configuration.storageBucket,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: Configuration.iosApiKey,
    appId: Configuration.iosAppId,
    messagingSenderId: Configuration.messagingSenderId,
    projectId: Configuration.projectId,
    storageBucket: Configuration.storageBucket,
    iosClientId: Configuration.iosClientId,
    iosBundleId: Configuration.iosBundleId,
  );
}
